[package]
name = "kornia-rs"
version = "0.0.9"
edition = "2021"

[dependencies]
image = { version = "0.24.5" }
turbojpeg = {version = "0.5.2"}
ndarray = { version = "0.15.6" }

[dev-dependencies]
tempfile = "3.9.0"