[package]
name = "kornia_rs"
version = "0.0.9"
edition = "2021"

[dependencies]
pyo3 = { version = "0.20" }
image = { version = "0.24.5" }
dlpack-rs = {version = "^0.1.1"}
vviz = {version = "0.3.0", optional = true}
turbojpeg = {version = "0.5.2"}
#sophus-rs = {git="https://github.com/farm-ng/sophus-rs.git"}
sophus-rs = {path = "../sophus-rs"}

[dev-dependencies]
criterion = "0.5"
pprof = { version = "0.13", features = ["flamegraph"] }
tempfile = "3.9.0"

[[bench]]
name = "my_benchmark"
harness = false

[features]
default = []
viz = ["dep:vviz"]
