[package]
name = "kornia_rs"
version = "0.0.8"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "kornia_rs"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.17.3", features = ["extension-module"] }
image = { version = "0.24.5" }
dlpack-rs = {version = "^0.1.1"}
vviz = {version = "0.3.0", optional = true}
turbojpeg = {version = "0.5.2"}
sophus-rs = {git="https://github.com/farm-ng/sophus-rs.git"}

[dev-dependencies]
criterion = "0.3"
pprof = { version = "0.3", features = ["flamegraph"] }

[[bench]]
name = "my_benchmark"
harness = false

[features]
default = []
viz = ["dep:vviz"]
