[package]
name = "kornia-rs"
version = "0.0.1"
edition = "2021"
description = "Low-level computer vision library in Rust"
homepage = "http://kornia.org"
repository = "https://github.com/kornia/kornia-rs"
categories = ["image-processing", "computer-vision", "machine-learning"]
license-file = "LICENSE"

[dependencies]
image = { version = "0.24.5" }
turbojpeg = {version = "0.5.2"}
ndarray = { version = "0.15.6", features = ["rayon"] }

[dev-dependencies]
tempfile = "3.9.0"
rerun = "0.12.1"
criterion = { version = "0.5.1", features = ["html_reports"] }
candle-core = "0.3.2"

[[bench]]
name = "color_benchmark"
harness = false

[[bench]]
name = "imgproc_benchmark"
harness = false
