[build]
default-target = "x86_64-unknown-linux-gnu"

[target.x86_64-unknown-linux-gnu]
dockerfile = "./docker/devel-x86_64.Dockerfile"

[target.aarch64-unknown-linux-gnu]
dockerfile = "./docker/devel-aarch64.Dockerfile"