[package]
name = "py-kornia-rs"
version = "0.1.0"
edition = "2021"

[lib]
name = "kornia_rs"
crate-type = ["cdylib"]

[dependencies]
kornia-rs = { path = ".." }
dlpack-rs = {version = "^0.1.1"}
pyo3 = { version = "0.20", features = ["extension-module"] }
numpy = "0.20.0"
